kind: pipeline
name: default

steps:
- name: Setup
  image: debian:buster
  environment:
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
  commands:
  - apt-get update && apt-get install -y sudo curl git-core bzip2 zip gnupg make gcc libssl-dev libreadline-dev zlib1g-dev postgresql-contrib libpq-dev build-essential phantomjs
  - export PATH="$HOME/.rbenv/bin:$PATH"
  - export PATH="$HOME/.rbenv/shims:$PATH"
  - curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
  #- rbenv init
  - rbenv install 2.6.5
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get -y install yarn
  - gem install bundler
  - gem install rails
  - bundle install
  - yarn install
  - rails db:create db:migrate
  - timeout --preserve-status -v 20 rails server || exit 0; echo $?

services:
- name: postgres
  image: postgres:10-alpine
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    POSTGRES_HOST_AUTH_METHOD: trust