---
kind: pipeline
name: Test

steps:
- name: Install Bundles
  image: ruby:2.7.2
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - gem install bundler
  - gem install rails
  - bundle install

- name: Migrate Database
  image: ruby:2.7.2
  environment:
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - rails db:create db:migrate

- name: Test Server
  image: ruby:2.7.2
  environment:
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
    RAILS_ENV: test
  volumes:
  - name: bundle
    path: /usr/local/bundle
  - name: executables
    path: /usr/bin
  commands:
  - rails server -d
  - sleep 20
  - kill $(cat tmp/pids/server.pid)
  
services:
- name: postgres
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    POSTGRES_HOST_AUTH_METHOD: trust

volumes:
- name: bundle
  temp: {}
- name: executables
  temp: {}  
  
---
kind: pipeline
type: docker
name: Deploy
steps:

- name: Deploy Production
  image: appleboy/drone-ssh
  settings:
    host: 
        from_secret: SSH_HOST
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service phoenix restart
  when:
    event:
    - promote
    target:
    - production

- name: Deploy Staging
  image: appleboy/drone-ssh
  settings:
    host: 
        from_secret: SSH_HOST
    username:
        from_secret: SSH_USER
    key:
        from_secret: SSH_KEY
    port: 22
    script:
      - service phoenix_staging restart
  when:
    event:
    - promote
    target:
    - staging
    
trigger:
  branch:
    - master
  event:
    include:
      - promote
      - cron
depends_on:
  - Test
   
  
---
kind: signature
hmac: cd /mnt/e/RubymineProjects/edit.tosdr.org/

...
